package model;

import java.io.Serializable;
import java.util.HashMap;  
import java.util.List;  
import java.util.Map;  
  

@SuppressWarnings("serial")
public class FormPaises implements Serializable{
	
	private List<String> paisesSelecionados;  
	  
    private Map<String,String> paises;  
  
    public FormPaises() {  
        paises = new HashMap<String, String>();  
        paises.put("Afeganistão",
        		paises.put("África do Sul",
        		paises.put("Akrotiri"
        		paises.put("Albâniapaises"
        		paises.put("Alemanha"
        		paises.put("Andorra"
        		paises.put("Angola"
        		paises.put("Anguila"
        		paises.put("Antárctida"
        		paises.put("Antígua e Barbuda"
        		paises.put("Antilhas Neerlandesas"
        		paises.put("Arábia Saudita"
        		paises.put("Arctic Ocean"
        		paises.put("Argélia"
        		paises.put("Argentina"
        		paises.put("Arménia"
        		paises.put("Aruba"
        		paises.put("Ashmore and Cartier Islands"
        		paises.put("Atlantic Ocean"
        		paises.put("Áustria"
        		paises.put("Austrália"
        		paises.put("Azerbaijão"
        		paises.put("Baamas"
        		paises.put("Bangladeche"
        		paises.put("Barbados"
        		paises.put("Barém"
        		paises.put("Bélgica"
        		paises.put("Belize"
        		paises.put("Benim"
        		paises.put("Bermudas"
        		paises.put("Bielorrússia"
        		paises.put("Birmânia
        		paises.put("Bolívia"
        		paises.put("Bósnia e Herzegovina"
        		paises.put("Botsuana"
        		paises.put("Brasil"
        		paises.put("Brunei"
        		paises.put("Bulgária"
        		paises.put("Burquina Faso"
        		paises.put("Burúndi"
        		paises.put("Butão"
        		paises.put("Cabo Verde"
        		paises.put("Camarões"
        		paises.put("Camboja"
        		paises.put("Canadá"
        		paises.put("Catar"
        		paises.put("Cazaquistão"
        		paises.put("Chade"
        		paises.put("Chile"
        		paises.put("China"
        		paises.put("Chipre"
        		paises.put("Clipperton Island"
        		paises.put("Colômbia"
        		paises.put("Comores"
        		paises.put("Congo-Brazzaville"
        		paises.put("Congo-Kinshasa"
        		paises.put("Coral Sea Islands
        		paises.put("Coreia do Norte"
        		paises.put("Coreia do Sul"
        		paises.put("Costa do Marfim"
        		paises.put("Costa Rica"
        		paises.put("Croácia"
        		paises.put("Cuba"
        		paises.put("Dhekelia"
        		paises.put("Dinamarca""
        		paises.put("Domínica"
        		paises.put("Egipto"
        		paises.put("Emiratos Árabes Unidos"
        		paises.put("Equador"
        		paises.put("Eritreia"
        		paises.put("Eslováquia"
        		paises.put("Eslovénia"
        		paises.put("Espanha"
        		paises.put("Estados Unidos"
        		paises.put("Estónia"
        		paises.put("Etiópia"
        		paises.put("Faroé"
        		paises.put("Fiji"
        		paises.put("Filipinas"
        		paises.put("Finlândia"
        		paises.put("França"
        		paises.put("Gabão"
        		paises.put("Gâmbia"
        		paises.put("Gana"
        		paises.put("Gaza Strip"
        		paises.put("Geórgia"
        		paises.put("Geórgia do Sul e Sandwich do Sul"
        		paises.put("Gibraltar"
        		paises.put("Granada"
        		paises.put("Grécia"
        		paises.put("Gronelândia"
        		paises.put("Guame"
        		paises.put("Guatemala"
        		paises.put("Guernsey"
        		paises.put("Guiana"
        		paises.put("Guiné"
        		paises.put("Guiné Equatorial"
        		paises.put("Guiné-Bissau"
        		paises.put("Haiti"
        		paises.put("Honduras"
        		paises.put("Hong Kong"
        		paises.put("Hungria"
        		paises.put("Iémen"
        		paises.put("Ilha Bouvet"
        		paises.put("Ilha do Natal"
        		paises.put("Ilha Norfolk"
        		paises.put("Ilhas Caimão"
        		paises.put("Ilhas Cook"
        		paises.put("Ilhas dos Cocos"
        		paises.put("Ilhas Falkland"
        		paises.put("Ilhas Heard e McDonald"
        		paises.put("Ilhas Marshall"
        		paises.put("Ilhas Salomão"
        		paises.put("Ilhas Turcas e Caicos"
        		paises.put("Ilhas Virgens Americanas"
        		paises.put("Ilhas Virgens Britânicas"
        		paises.put"Índia"
        		paises.put("Indian Ocean"
        		paises.put("Indonésia"
        		paises.put("Irão"
        		paises.put("Iraque"
        		paises.put("Irlanda"
        		paises.put("Islândia"
        		paises.put("Israel"
        		paises.put("Itália"
        		paises.put("Jamaica"
        		paises.put("Jan Mayen"
        		paises.put("Japão"
        		paises.put("Jersey"
        		paises.put("Jibuti"
        		paises.put("Jordânia"
        		paises.put("Kuwait"
        		paises.put("Laos"
        		paises.put("Lesoto"
        		paises.put("Letónia"
        		paises.put("Líbano"
        		paises.put("Libéria"
        		paises.put("Líbia"
        		paises.put("Listenstaine"
        		paises.put("Lituânia"
        		paises.put("Luxemburgo"
        		paises.put("Macau"
        		paises.put("Macedónia"
        		paises.put("Madagáscar"
        		paises.put("Malásia"
        		paises.put("Malávi"
        		paises.put("Maldivas"
        		paises.put("Mali"
        		paises.put("Malta"
        		paises.put("Man, Isle of"
        		paises.put("Marianas do Norte"
        		paises.put("Marrocos"
        		paises.put("Maurícia"
        		paises.put("Mauritânia"
        		paises.put("Mayotte"
        		paises.put("México"
        		paises.put("Micronésia"
        		paises.put("Moçambique"
        		paises.put("Moldávia"
        		paises.put("Mónaco"
        		paises.put("Mongólia"
        		paises.put("Monserrate"
        		paises.put("Montenegro"
        		paises.put("Mundo"
        		paises.put("Namíbia"
        		paises.put("Nauru"
        		paises.put("Navassa Island"
        		paises.put("Nepal"
        		paises.put("Nicarágua"
        		paises.put("Níger"
        		paises.put("Nigéria"
        		paises.put("Niue"
        		paises.put("Noruega"
        		paises.put("Nova Caledónia"
        		paises.put("Nova Zelândia"
        		paises.put("Omã"
        		paises.put("Pacific Ocean"
        		paises.put("Países Baixos"
        		paises.put("Palau"
        		paises.put("Panamá"
        		paises.put("Papua-Nova Guiné"
        		paises.put("Paquistão"
        		paises.put("Paracel Islands"
        		paises.put("Paraguai"
        		paises.put("Peru"
        		paises.put("Pitcairn"
        		paises.put("Polinésia Francesa"
        		paises.put("Polónia"
        		paises.put("Porto Rico"
        		paises.put("Portugal"
        		paises.put("Quénia"
        		paises.put("Quirguizistão"
        		paises.put("Quiribáti"
        		paises.put("Reino Unido"
        		paises.put("República Centro-Africana"
        		paises.put("República Checa"
        		paises.put("República Dominicana"
        		paises.put("Roménia"
        		paises.put("Ruanda"
        		paises.put("Rússia"
        		paises.put("Salvador"
        		paises.put("Samoa"
        		paises.put("Samoa Americana"
        		paises.put("Santa Helena"
        		paises.put("Santa Lúcia"
        		paises.put("São Cristóvão e Neves"
        		paises.put("São Marinho"
        		paises.put("São Pedro e Miquelon"
        		paises.put("São Tomé e Príncipe"
        		paises.put("São Vicente e Granadinas"
        		paises.put("Sara Ocidental"
        		paises.put("Seicheles"
        		paises.put("Senegal"
        		paises.put("Serra Leoa"
        		paises.put("Sérvia"
        		paises.put("Singapura"
        		paises.put("Síria"
        		paises.put("Somália"
        		paises.put("Southern Ocean"
        		paises.put("Spratly Islands"
        		paises.put("Sri Lanca"
        		paises.put("Suazilândia"
        		paises.put("Sudão"
        		paises.put("Suécia"
        		paises.put("Suíça"
        		paises.put("Suriname"
        		paises.put("Svalbard e Jan Mayen"
        		paises.put("Tailândia"
        		paises.put("Taiwan"
        		paises.put("Tajiquistão"
        		paises.put("Tanzânia"
        		paises.put("Território Britânico do Oceano Índico"
        		paises.put("Territórios Austrais Franceses"
        		paises.put("Timor Leste"
        		paises.put("Togo"
        		paises.put("Tokelau"
        		paises.put("Tonga"
        		paises.put("Trindade e Tobago"
        		paises.put("Tunísia"
        		paises.put("Turquemenistão"
        		paises.put("Turquia"
        		paises.put("Tuvalu"
        		paises.put("Ucrânia"
        		paises.put("Uganda"
        		paises.put("União Europeia"
        		paises.put("Uruguai"
        		paises.put("Usbequistão"
        		paises.put("Vanuatu"
        		paises.put("Vaticano"
        		paises.put("Venezuela"
        		paises.put("Vietname"
        		paises.put("Wake Island"
        		paises.put("Wallis e Futuna"
        		paises.put("West Bank"
        		paises.put("Zâmbia"
        		paises.put("Zimbabué"
    }  
  
    public List<String> getSelectedMovies() {  
        return paisesSelecionados;  
    }  
    public void setSelectedMovies(List<String> selectedMovies) {  
        this.paisesSelecionados = selectedMovies;  
    }  
  
    public Map<String, String> getMovies() {  
        return paises;  
    }  

}
